/**
 * The early-warning detector's design constants, in one dependency-free
 * module so the production engine (`earlyWarningEngine.ts`) and the offline
 * evaluation harness (`src/evaluation/`) provably run the SAME design --
 * the evaluation can't quietly characterise a detector that isn't the one
 * that ships. Change a value here and both move together; EVALUATION.md is
 * regenerated by `npm run evaluate` and a test fails if it goes stale.
 */

/** EWMA smoothing constant (see ewma.ts). */
export const EWMA_LAMBDA = 0.25;

/** EWMA control-limit width in standard deviations. */
export const EWMA_L = 3;

/** A station must be statistically out-of-control for this many
 * *consecutive* ticks before it is auto-escalated to a confirmed exposure.
 * Chosen from the measured trade-off in EVALUATION.md (false-escalation
 * rate vs detection delay), not by intuition. */
export const ESCALATION_THRESHOLD_TICKS = 5;

/** Severity assigned to an auto-escalated confirmation -- a fixed,
 * documented value distinct from an operator's default 0.9 (a human
 * directly reporting ground truth), since this is inferred from a
 * statistical signal rather than observed directly. */
export const AUTO_ESCALATION_SEVERITY = 0.7;
